"""
PR failure auto-triage.

Reads the failing step log and classifies the failure into the
taxonomy defined in docs/governance/PR_FAILURE_PROTOCOL.md.

Usage:
  python scripts/_pr_triage.py --workflow debug-single-transcript
  python scripts/_pr_triage.py --log-text "error: no meeting_extraction artifact"
  echo "..." | python scripts/_pr_triage.py --log-text -

Outputs a structured triage result to stdout. Exit codes:
  0 = INFRASTRUCTURE (no code change needed)
  1 = LOGIC FAILURE (code change needed, class in stdout)
  2 = triage inconclusive (needs human review)
"""
import argparse
import json
import re
import sys

# Failure pattern -> class mapping
PATTERNS = [
    # Infrastructure
    (r"pyo3_runtime\.PanicException", "INFRASTRUCTURE",
     "Missing C binding in CI runner environment"),
    (r"_cffi_backend", "INFRASTRUCTURE",
     "Python cryptography extension not compiled"),
    (r"No space left on device", "INFRASTRUCTURE",
     "CI runner disk full"),
    (r"Connection refused|Network unreachable|timeout", "INFRASTRUCTURE",
     "CI network failure"),

    # Schema drift
    (r"Additional properties are not allowed", "SCHEMA_DRIFT",
     "Artifact has field not in schema"),
    (r"artifact_type.*expected.*got|got.*artifact_type.*expected", "SCHEMA_DRIFT",
     "Wrong artifact_type field value"),

    # Gitignore / path
    (r"pathspec.*did not match any files", "GITIGNORE_PATH",
     "git add targeting a path that doesn't exist or is gitignored"),
    (r"no meeting_extraction artifact found", "GITIGNORE_PATH",
     "Extraction artifact not committed - likely gitignored"),

    # Sequencing gap
    (r"matched 0 pairs|Available identifiers.*\[\]", "SEQUENCING_GAP",
     "Required input artifact not generated by prior step"),
    (r"chunks_jsonl_not_found", "SEQUENCING_GAP",
     "Ingestion step didn't produce chunks.jsonl"),
    (r"source_artifact_id.*None|resolved.*None", "SEQUENCING_GAP",
     "source_record.json missing or not committed"),

    # Contract mismatch
    (r"KeyError|AttributeError.*NoneType", "CONTRACT_MISMATCH",
     "Script reading field that doesn't exist in artifact"),

    # Branch protection
    (r"GH006.*Protected branch", "INFRASTRUCTURE",
     "Branch protection blocking direct push - not a code failure"),

    # Placeholder
    (r"phase-v-placeholder", "CONTRACT_MISMATCH",
     "Placeholder IDs survived into production artifact"),
]


def classify(log_text: str) -> dict:
    for pattern, cls, reason in PATTERNS:
        if re.search(pattern, log_text, re.IGNORECASE):
            return {
                "class": cls,
                "reason": reason,
                "pattern_matched": pattern,
                "is_infrastructure": cls == "INFRASTRUCTURE",
            }
    return {
        "class": "UNKNOWN",
        "reason": "No pattern matched - needs human review",
        "pattern_matched": None,
        "is_infrastructure": False,
    }


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--log-text", help="Log text to classify, or '-' to read from stdin")
    parser.add_argument("--pr-number", help="PR number for context (informational)")
    parser.add_argument("--workflow", help="Workflow name for context")
    args = parser.parse_args()

    if not args.log_text:
        print("ERROR: --log-text required (pipe from 'gh run view --log' with --log-text -)")
        sys.exit(2)

    if args.log_text == "-":
        log_text = sys.stdin.read()
    else:
        log_text = args.log_text

    result = classify(log_text)
    print(json.dumps(result, indent=2))

    if result["class"] == "UNKNOWN":
        sys.exit(2)
    elif result["is_infrastructure"]:
        print("\nINFRASTRUCTURE FAILURE: No code change needed.")
        print("Document in docs/governance/known_infrastructure_failures.md")
        sys.exit(0)
    else:
        print(f"\nLOGIC FAILURE: Class={result['class']}")
        print("Read docs/governance/PR_FAILURE_PROTOCOL.md for repair protocol.")
        sys.exit(1)


if __name__ == "__main__":
    main()
